version: "3"
services:
    web:
        image: "my_blog:latest"
        ports:
            - "5000:5000"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "Kleopatra2017@@"
            ACCEPT_EULA: "Y"